version: '2.4'
x-net: &net
  networks:
      - main
services:
  db:
    <<: *net
    image: datajoint/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=coogs
    # ports:
    #   - "3306:3306"
    # To persist MySQL data
    # volumes:
    #   - ./mysql/data:/var/lib/mysql
    #   - ./mysql/my.cnf:/etc/mysql/my.cnf
  app:
    <<: *net
    # build:
    #   context: .
    image: raphaelguzman/uh_demo:0.0.0
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - DJ_PASS=coogs
      - PYTHON_USER=dja
      - JUPYTER_PASSWORD=coogs
      - DISPLAY
    working_dir: /home/dja/notebooks
    command: >
      /bin/sh -c
       "
        # conda install -yc conda-forge datajoint;
        jupyter lab;
       "
    ports:
      - "8888:8888"
    user: 1000:anaconda
    volumes:
      - ./apk_requirements.txt:/apk_requirements.txt
      - ./pip_requirements.txt:/pip_requirements.txt
      - ./conda_requirements.txt:/conda_requirements.txt
      # - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Additional mounted notebooks may go here
      - ./notebook:/home/dja/notebooks
networks:
  main: